django/0316/mypjt/myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('articles/', views.articles, name='articles'),
    path('create/', views.create, name='create'),
    path('delete/', views.delete, name='delete'),
    path('new/', views.new, name='new'),
    path('remv/', views.remv, name='remv'),

]

django/0316/mypjt/myapp/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()


    def __str__(self):
        return f'제목 : {self.title} / 내용 : {self.content}'

django/0316/mypjt/myapp/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    return render(request, 'myapp/index.html')


def throw(request):
    return render(request, 'myapp/throw.html')


def catch(request):
    message = request.GET.get('message')
    context  = {
        'message':message
    }
    return render(request, 'myapp/catch.html', context)


def articles(request):
    articles = Article.objects.all()
    context = {
        'articles' : articles,
    }
    return render(request, 'myapp/articles.html', context)



def create(request):
    return render(request, 'myapp/create.html')

def delete(request):
    return render(request, 'myapp/delete.html')


# 데이터를 DB에 저장
def new(request):
    # 데이터 받아오기
    title = request.POST.get('title')
    content = request.POST.get('content')
    # DB에 저장
    Article.objects.create(title=title, content=content)
    # 생성 후 전체 목록 리스트로 가야함
    
    # myapp:articles로 요청을 다시 보냄
    return redirect('myapp:articles')

def remv(request):
    id = request.POST.get('id')
    article = Article.objects.get(id=id)
    article.delete()

    return redirect('myapp:articles')

django/0316/mypjt/myapp/templates/myapp/articles.html
{% extends 'base.html' %}

{% block temp %}

    <h1>전체 조회 페이지</h1>
    {% for article in articles  %}
    <p>글 번호 : {{article.pk}}</p>
    <p>제목 : {{article.title}}</p>
    <p>내용 : {{article.content}}</p>
    
    <a href="{% url 'myapp:delete' %}">삭제하기</a>
    <hr>
    {% endfor %} 

    {% comment %} {{articles}} {% endcomment %}
{% endblock temp %}

django/0316/mypjt/myapp/templates/myapp/catch.html
{% extends 'base.html' %}

{% block temp %}
    <h1>catch</h1>
    <h2>보낸 데이터 : {{ message }}</h2>

    <a href="{% url 'myapp:throw' %}">다시 데이터 보내</a>
{% endblock temp %}

django/0316/mypjt/myapp/templates/myapp/create.html
{% extends 'base.html' %}

{% block temp %}
<h1>생성 페이지</h1>

<form action="{% url 'myapp:new' %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="">제목 : </label>
        <input type="text" name="title">
    </div> 
    <div>
        <label for="">내용 : </label>
        <input type="text" name="content">
    </div> 
    <input type="submit" value="생성하기">
</form>
{% endblock temp %}

django/0316/mypjt/myapp/templates/myapp/delete.html
{% extends 'base.html' %}

{% block temp %}
<h1>DB 삭제</h1>

<form action="{% url 'myapp:remv' %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="">id : </label>
        <input type="number" name="id">
    </div> 
    
    <input type="submit" value="삭제하기">
</form>
{% endblock temp %}

django/0316/mypjt/myapp/templates/myapp/index.html
{% extends 'base.html' %}

{% block temp %}
    <h1>인덱스 페이지</h1>
{% endblock temp %}

django/0316/mypjt/myapp/templates/myapp/throw.html
{% extends 'base.html' %}

{% block temp %}
    <h1>throw</h1>

    <form action="{% url 'myapp:catch' %}" method="GET">
        <label for="message">Throw</label>
        <input type="text" id="message" name="message">
        <input type="submit">

    </form>
{% endblock temp %}