django/0325/mypjt/myapps/urls.py
from django.urls import path
from . import views

app_name = 'myapps'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
]

django/0325/mypjt/myapps/models.py
from django.db import models

# Create your models here.
class Myapp(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    image = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

django/0325/mypjt/myapps/forms.py
from django import forms
from .models import Myapp

class MyappForm(forms.ModelForm):

    class Meta:
        model = Myapp
        fields = '__all__'

django/0325/mypjt/myapps/views.py
from django.shortcuts import render, redirect
from .models import Myapp
from .forms import MyappForm

# Create your views here.
def index(request):
    myapps = Myapp.objects.all()
    context = {
        'myapps':myapps
    }
    response = render(request, 'myapps/index.html', context)
    response.set_cookie('message', 'wow')
    return response
    


def detail(request, pk):
    myapp = Myapp.objects.get(pk=pk)
    context = {
        'myapp':myapp,
    }
    return render(request, 'myapps/detail.html', context)


def create(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    if request.method == 'POST':
        form = MyappForm(request.POST, request.FILES)
        if form.is_valid():
            myapp = form.save()
            return redirect('myapps:detail', myapp.pk)
    else:
        form = MyappForm()
    
    context = {'form':form}
    return render(request, 'myapps/create.html', context)

def delete(request, pk):
    myapp = Myapp.objects.get(pk=pk)
    myapp.delete()
    return redirect('myapps:index')


def update(request, pk):
    myapp = Myapp.objects.get(pk=pk)
    if request.method=="POST":
        form = MyappForm(request.POST, request.FILES, instance=myapp)
        if form.is_valid():
            form.save()
            return redirect('myapps:detail', pk=myapp.pk)
    else:
        form = MyappForm(instance=myapp)

    context = {
        'form':form, 'myapp' : myapp
    }
    return render(request, 'myapps/update.html', context)

django/0325/mypjt/myapps/templates/myapps/create.html
{% extends 'base.html' %}
{% block content %}
    <h1>CREATE</h1>
    <hr>
    <form action="{% url 'myapps:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="작성하기"/>
    </form>
    
    <a href="{% url 'myapps:index' %}">[Back]</a>
{% endblock content %}

django/0325/mypjt/myapps/templates/myapps/detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>DETAIL</h1>
    <hr>
    {% if myapp.image %}
      <img src="{{myapp.image.url}}" />
    {% endif %}
    <p> 글 제목 : {{myapp.title}} </p>
    <p> 글 내용 : {{myapp.content}} </p>
    <p> 생성시각 : {{myapp.created_at}} </p>
    <p> 수정시각 : {{myapp.updated_at}} </p>
    <hr>
    <form action="{% url 'myapps:delete' myapp.pk %}">
        <input type="submit" value="삭제하기" />
    </form>
    <a href="{% url 'myapps:update' myapp.pk %}">[update]</a>
    <br>
    <a href="{% url 'myapps:index' %}">[Back]</a>
{% endblock content %}

django/0325/mypjt/myapps/templates/myapps/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>INDEX</h1>
    <a href="{% url 'myapps:create' %}">[생성하기]</a>
    {% if myapps %}
        {% for myapp in myapps %}
        <a href="{% url 'myapps:detail' myapp.pk %}">
        <p>{{myapp.title}}</p>
        </a>
        {% endfor %}
    {% else %}
        <p>게시글이 없습니다.</p>
    {% endif %}
    
    
    
{% endblock content %}

django/0325/mypjt/myapps/templates/myapps/update.html
{% extends 'base.html' %} 

{% block content %}
  <h1>UPDATE</h1>
  <hr />

  <form action="{% url 'myapps:update' myapp.pk %}" method="POST"  enctype='multipart/form-data'>
    {% csrf_token %} {{form.as_p}}
    <input type="submit" />
  </form>

  <hr />
  <a href="{% url 'myapps:detail' myapp.pk %}">돌아가기</a>
{% endblock content %}