django/0316/problem2/calculation/urls.py
from django.urls import path
from . import views

app_name = 'calculation'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('calculation/', views.throw, name='throw'),
    path('result/', views.catch, name='catch'),
]

django/0316/problem2/problem2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('calculation.urls')),
]

django/0316/problem2/calculation/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'calculation/index.html')

def throw(request):
    return render(request, 'calculation/throw.html')

def catch(request):
    number1 = int(request.GET.get('number1'))
    number2 = int(request.GET.get('number2'))
    context = {
        'number1': number1,
        'number2': number2,
        'num1' : number1 - number2,
        'num2' : number1 * number2,
        'num3' : number1 / number2 if number2 != 0 else '',

    }
    return render(request, 'calculation/catch.html', context)

django/0316/problem2/calculation/templates/calculation/catch.html
{% extends 'base.html' %}

{% block temp %}
    <h1>계산결과</h1>
    <p> {{ number1 }} + {{ number2 }} = {{ number1|add:number2 }} </p>
    <p> {{ number1 }} - {{ number2 }} = {{ num1 }} </p>
    <p> {{ number1 }} * {{ number2 }} = {{ num2 }} </p>
    {% if number2 == 0 %}
        <P>계산할 수 없습니다.</P>
    {% else %}
        <p> {{ number1 }} / {{ number2 }} = {{ num3 }} </p>
    {% endif %}
    
    <a href="{% url 'calculation:throw' %}">다시 던져</a>
    
{% endblock temp %}

django/0316/problem2/calculation/templates/calculation/index.html
{% extends 'base.html' %}


{% block temp %}
    <h1>인덱스 페이지</h1>
    <a href="{% url 'calculation:throw' %}">throw</a>
{% endblock temp %}

django/0316/problem2/calculation/templates/calculation/throw.html
{% extends 'base.html' %}

{% block temp %}
    <h1>연산할 두 숫자를 입력하세요</h1>
    <form action="{% url 'calculation:catch' %}" method="GET">
        <label for="number1">첫번째 숫자</label>
        <input type="number" id="number1" name="number1">
        <label for="number2">두번째 숫자</label>
        <input type="number" id="number2" name="number2">
        <input type="submit">

    </form>
{% endblock temp %}

django/0316/problem2/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block temp %}
        <h2>base</h2>
    {% endblock temp%}
    
</body>
</html>